---
language: go
go:
  - "1.12.x"
gobuild_args: -ldflags "-X \"main.BuildVersion=$TRAVIS_TAG\" -X \"main.BuildGitCommit=$TRAVIS_COMMIT\""
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep version
  - dep status
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
  - golangci-lint --version
script:
  - golangci-lint run
  - make
