---
server:
  # Proxy API listener:
  listenAddress: "127.0.0.1:8000"
  tls:
    # Let dyndns-pdns terminate the TLS session:
    enable: true
    # TLS certificate file:
    certFile: "server.crt"
    # TLS key file:
    keyFile: "server.key"

powerDNS:
  # PowerDNS API base URL:
  baseURL: "http://127.0.0.1:8080/"
  # PowerDNS vHost (usually "localhost"):
  vhost: "localhost"
  # PowerDNS API key:
  apiKey: "secret"
  # DNS zone that is containing the dynamic resource records:
  zone: "dyn.example.com"
  # Default TTL for TXT records (might be overwritten by the key table):
  defaultTTL: 10

keyTable:
- name: "homeRouter"
  enable: true
  key: "secret"
  # DNS hostname (will be concatenated to "${hostName}.${miscellaneous.zone}"):
  hostName: "home-router"
  # Choose ingestMode between "getParameter" and "remoteAddress" (see README.md for further information):
  ingestMode: "getParameter"
  # Overwrite miscellaneous.defaultTTL:
  ttl: 5
- name: "officeRouter"
  enable: true
  key: "topSecret"
  hostName: "office-router"
  ingestMode: "remoteAddress"
