---
name: Tests
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          $(go env GOPATH)/bin/staticcheck ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.19]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goVer }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Make
        run: make
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: c.out
          outfile: c.lcov
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: c.lcov
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
